### ISSUE TITLE
Feature request: Return every movie with the specified title, independent of release year

### ISSUE THREAD

**Issue by backflip** [omdbapi/OMDb-API#10]
Currently, the API is only returning a single result for every title. In case of `The Italian Job`, it returns the movie from 2003 unless explicitly specifying `y=1969` as additional parameter. Any chance it could return an array of matching movies instead?

**Comment by helderroem** [comment]
you can get an array of  matching movies using the `s` parameter, you can further filter the results using `type=movie`:
  `http://www.omdbapi.com/?s=The%20Italian%20Job&type=movie`

this brings back more than the 2 movies though.

**Comment by backflip** [comment]
Awesome, thanks! I didn't realize that there was a `s` parameter since I only checked the [Examples section](https://www.omdbapi.com/#examples)...
