### ISSUE TITLE
getting "No API key provided" error 

### ISSUE THREAD

**Issue by vigneshkm** [omdbapi/OMDb-API#107]
Hi,

I am trying to query OMDB API with query "curl http://www.omdbapi.com/?t=titanic" but I get following response:
{"Response":"False","Error":"No API key provided."}

I got the query from "Examples" section at "http://omdbapi.com/". Kindly let me know if I am missing some thing or if something is wrong at OMDB API.

Thanks,
Vignesh

**Comment by dewey** [comment]
As the error message says you need to provide an API key.

**Comment by vigneshkm** [comment]
@dewey thank you for your response.. I didnt knew about apikey. I then generated one for myself but now getting new error.

query :"curl http://www.omdbapi.com/?apikey=XXXXXXXX&t=titanic"
error:
{"Response":"False","Error":"Something went wrong."}

Thanks,
Vignesh

**Comment by torben-w** [comment]
You can't just generate an API key. You need to get one from the website.

**Comment by vigneshkm** [comment]
@torben-w I had got one from website itself (http://omdbapi.com/apikey.aspx), 8 digit key

**Comment by dewey** [comment]
```
curl "http://www.omdbapi.com?apikey=xxxxxxx&t=titanic"
```

this works for me, also all your requests that you posted work with my key.

**Comment by vigneshkm** [comment]
oh.. I was using wrong syntax, was not having query within double quotes. Works now.. Thanks a lot @dewey

**Comment by umDante** [comment]
Ojo al usar http:// o https://
