### ISSUE TITLE
API Response Example

### ISSUE THREAD

**Issue by robax** [omdbapi/OMDb-API#109]
I'm fine with the API being private, and I'm considering becoming a patron for access. However, I can't find any examples of what kind of data the API provides (the homepage examples are broken).

If anyone could provide an example response I would greatly appreciate it, but the bigger problem is that the homepage examples need to be updated.

**Comment by MAGICCC** [comment]
The examples are working for me when you mean the forms
e.g.
```
{
"Title": "Star Wars: Episode IV - A New Hope",
"Year": "1977",
"Rated": "PG",
"Released": "25 May 1977",
"Runtime": "121 min",
"Genre": "Action, Adventure, Fantasy, Sci-Fi",
"Director": "George Lucas",
"Writer": "George Lucas",
"Actors": "Mark Hamill, Harrison Ford, Carrie Fisher, Peter Cushing",
"Plot": "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.",
"Language": "English",
"Country": "USA",
"Awards": "Won 6 Oscars. Another 50 wins & 28 nominations.",
"Poster": "https://m.media-amazon.com/images/M/MV5BNzVlY2MwMjktM2E4OS00Y2Y3LWE3ZjctYzhkZGM3YzA1ZWM2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
"Ratings": [
{
"Source": "Internet Movie Database",
"Value": "8.6/10"
},
{
"Source": "Rotten Tomatoes",
"Value": "93%"
},
{
"Source": "Metacritic",
"Value": "90/100"
}
],
"Metascore": "90",
"imdbRating": "8.6",
"imdbVotes": "1,092,532",
"imdbID": "tt0076759",
"Type": "movie",
"DVD": "21 Sep 2004",
"BoxOffice": "N/A",
"Production": "20th Century Fox",
"Website": "http://www.starwars.com/episode-iv/",
"Response": "True"
}
```

You could use the API Key 'BanMePlz' for testing purposes I guess

**Comment by robax** [comment]
Thanks for the quick response @MAGICCC ! The testing forms respond to me with "Error: Daily Request Limit Reached!", even when using the BanMePlz API key. Maybe someone abused that API key today and hit the daily limit. :)

Anyway, thanks for the example. I'll likely become a patron soon. Closing this.
