### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by nathantaal** [omdbapi/OMDb-API#115]
The last update of the project seems to be the end of 2017, issues open from 2018 (where some seem high prio to me) with no reactions
Is this project dead..?

**Comment by tgreve15** [comment]
The source isn't on github, just the issues. There are some common issues
get raised that in my opinion could easily be mitigated with some basic
faq's (like where the data is sourced from not being imbd). Basically,
bigger problems are resolved fairly quickly, but not sure it is top
priority for owner for other things

**Comment by nathantaal** [comment]
No I understood about github being only used for issues, i based my question on the changelog part from the website. 
When someone wants to get a season that has 220 episodes, the request sends only 100 of them, and pagination doesn't work, then I understand it's exceptional and therefore low prio but I would at least expect some sort of reaction from omdbapi :)
But from your reaction I understand it's not dead and that is great

**Comment by Freddy12** [comment]
It looks quite dead actually.

Issues not being addressed at all. No comments from owner.

We do support via Patreon. At least fixing and improving API slowly would be cool.
