### ISSUE TITLE
Response depends on order of queries in query string

### ISSUE THREAD

**Issue by flopalko** [omdbapi/OMDb-API#120]
Hello,
I am using your awesome API in my app and it works perfectly. Recently, I had an issue with a specific episode and always got an error response.
{"Response":"False","Error":"Series or episode not found!"}

After hours of searching for the bug I found it: the response depends on the order of the queries. See examples below:

url: http://www.omdbapi.com/?t=Arrow&episode=17&season=7&apikey=[your_key]
response: {"Response":"False","Error":"Series or episode not found!"}

url: http://www.omdbapi.com/?t=Arrow&season=7&episode=17&apikey=[your_key]
response: {"Title":"Inheritance","Year":"2019".....

But, this does not occur often. In fact, this specific episode is the first time it happened in my app. For example, it works fine for "The Big Bang Theory", no matter the order of the queries.

Best regards

**Comment by omdbapi** [comment]
I could not duplicate this issue.

**Comment by flopalko** [comment]
I cannot duplicate this issue now as well. Yesterday it was reproducable, showed this behavior every time.
