### ISSUE TITLE
Plot

### ISSUE THREAD

**Issue by angelc16** [omdbapi/OMDb-API#136]
Hi, I want to get the complete plot of a movie using the method:
`http://www.omdbapi.com/?apikey=***&i=tt7284202&plot=full`
![withplot](https://user-images.githubusercontent.com/29113089/60939262-a34f6c80-a29c-11e9-9ee3-218fa42795bb.PNG)

I get the same result as using
`http://www.omdbapi.com/?apikey=***&i=tt7284202`
![withoutplot](https://user-images.githubusercontent.com/29113089/60939316-cc6ffd00-a29c-11e9-926d-23cf3ebaa2b3.PNG)
I think you should show the extended plot field
Correct me if I'm not applying it well, sorry for the bad English

**Comment by ohhsodead** [comment]
I may be wrong but I'm sure I noticed only some movies have a have full plot. Try different movies to see results.

**Comment by omdbapi** [comment]
Working as intended, if no full plot is available the API will return the summarized plot.
