### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by blairg23** [omdbapi/OMDb-API#138]
I'm seeing a lot of bugs that haven't been triaged or even replied to... is anyone curating this bug reporting repo?

**Comment by Freddy12** [comment]
Looks like pretty dead. I don't see any answers or fixes for more than a year now.

**Comment by pdonias** [comment]
Sad 😢

**Comment by omdbapi** [comment]
**04/08/19** - Added support for eight digit IMDb IDs.

4 months, not "more than a year".

Been a little busy the past few months (bought a house, moving, work etc.), I'll be posting some major features and improvements before the year ends.
