### ISSUE TITLE
Bug with poster addresses from ia.media-imdb.com

### ISSUE THREAD

**Issue by a-raccoon** [omdbapi/OMDb-API#143]
There is a bug in that your database contains poster addresses hosted on the media-imdb.com domain.  These all return as invalid request.

Example: [http://ia.media-imdb.com/images/M/MV5BMTEwMzIy(snip).jpg](http://ia.media-imdb.com/images/M/MV5BMTEwMzIyODQwOTheQTJeQWpwZ15BbWU4MDgwMjYxNzMx._V1_SX300.jpg)
Returns: `ERROR 403: Forbidden.`

Correct Address: [https://m.media-amazon.com/images/M/MV5BMTEwMzIy(snip).jpg](https://m.media-amazon.com/images/M/MV5BMTEwMzIyODQwOTheQTJeQWpwZ15BbWU4MDgwMjYxNzMx._V1_SX300.jpg)

Solution:  Perform a simple Search & Replace in your database...

Search for: http://ia.media-imdb.com/images/M/
Replace with: https://m.media-amazon.com/images/M/
(note, https should always be used. http is obsolete)

I believe the same should also be done with these addresses...

Search for: https://images-na.ssl-images-amazon.com/images/M/
Also replace with: https://m.media-amazon.com/images/M/
... just for consistency.  Both addresses work either way.

**Comment by omdbapi** [comment]
This has been addressed, thanks for the easy solution.

**Comment by a-raccoon** [comment]
@omdbapi is there any way that I might make edits to the database?  Do you have any sort of wiki editor or such?  shared google docs spreadsheet?
