### ISSUE TITLE
Error 522 when making a request

### ISSUE THREAD

**Issue by DzhideX** [omdbapi/OMDb-API#156]
I've been using your API for the last week every day 3 hours at a time practicing React making a 'relatively' complex site. The thing that pertains to this error is that I haven't made too many requests at a time. 

It is a movie search app where one can search for a movie, and then find more information about each movie. So firstly I make one search request and then one id request for each of the results. I've been making these same requests for a couple of days now but haven't had any issues until the last couple of hours.

Now when I try to make a request it gives me a connection timed out error(522). It is the same whether I try to access it from my code or the browser.. 

I have tried to find out if there are any limits to how many requests I can make in a day but I haven't found any information that is already easily accessible pertaining to that sort of information.

**Comment by Hairrison** [comment]
I have the same problem, All requests returns error 522

**Comment by Samuelloz** [comment]
i have the same problem too.

**Comment by DzhideX** [comment]
@Samuelloz @Hairrison  They're probably having server issues if we are all currently experiencing the same exact error. Might as well wait it out until tomorrow:/

**Comment by gregorioospina** [comment]
Im having the same issue! And I am using the API for a uni project due in 5 hours, there goes my semester :(

**Comment by Samuelloz** [comment]
You're right I'll wait until tomorrow :( thanks!

**Comment by josiahjswab** [comment]
i++

**Comment by omdbapi** [comment]
Hosting provider had a network failure.

I'm currently working on a offsite backup server that I can quickly switch the DNS to incase this ever happens again.
