### ISSUE TITLE
Change name to PMDb

### ISSUE THREAD

**Issue by dhershman1** [omdbapi/OMDb-API#16]
It's really not an open movie database anymore is it?

Should probably change the name to Private Movie Database

**Comment by omdbapi** [comment]
I beat you to that punch line months ago! Hence the "open" in quotes on the Patreon page. The API was open for 6+ years and will be again, I'm currently finishing up the free registration process now.

Making the API private was the only option I had available to reduce the traffic which was being abused by millions of people at **1.5+ BILLION requests a day** of mostly bots/scripts looping through tt0000000-tt9999999 24/7. Even today 93% of the traffic is unaccounted for of scripts/software still trying to hit the API without keys.
