### ISSUE TITLE
Kind testers needed

### ISSUE THREAD

**Issue by coolmatt** [omdbapi/OMDb-API#166]
Hi,

Sorry to raise an issue for something that is not, but here is the only place I could find to reach OMDb "enthusiasts" ;-) BTW, a forum on omdbapi.com would be nice...

Anyway, to the point : I made a Chrome extension and I really would appreciate some feedback. Is it working as expected, is something missing, is it useful at all ?

https://chrome.google.com/webstore/detail/movies-tv-shows-ratings/jlkcpmlnbhiaiidpblffbcnbfedogbfk

Thanks in advance.
M.A.

**Comment by omdbapi** [comment]
Looks great!
