### ISSUE TITLE
Get all titles of movies and series?

### ISSUE THREAD

**Issue by gdet** [omdbapi/OMDb-API#172]
Hello, 
is it possible to get all available titles of movies and series?

Thank you

**Comment by coolmatt** [comment]
Just curious... why would you want that ?

Imagine the amount of data returned !
And few hours after, there would be new entries anyway...

**Comment by eminsr** [comment]
It is not possible with OMDb-API but if you want everything you can get that data from IMDb [here](https://www.imdb.com/interfaces/). Just a reminder the data is in TSV format and It's updated daily.

**Comment by omdbapi** [comment]
Do you really want to page through 100+ million titles?
