### ISSUE TITLE
wrong tomatoURL

### ISSUE THREAD

**Issue by piramiday** [omdbapi/OMDb-API#173]
I have tried querying (e.g.) Donnie Yen's latest Ip Man movie, that is:
- imdb @ https://www.imdb.com/title/tt2076298
- rotten tomatoes @ https://www.rottentomatoes.com/m/ip_man_4_the_finale

unfortunately the following query:
```
https://www.omdbapi.com/?apikey=$KEY&tomatoes=true&i=tt2076298
```
returns a wrong `tomatoURL`:
```
  "tomatoURL": "http://www.rottentomatoes.com/m/771414063/",
```
which redirects to https://www.rottentomatoes.com/m/:vanity ...

is this expected? I was hoping to use OMDb to get _reliable_ results. :confused:
any help is appreciated! :wave:

**Comment by piramiday** [comment]
another case of wrong tomatoURL:
 - Tenet @ https://www.imdb.com/title/tt6723592/

the API at https://www.omdbapi.com/?i=tt6723592&tomatoes=true&apikey=X returns the following tomatoURL:
- https://www.rottentomatoes.com/m/untitled_wb_event_film_3

which replies (without redirects) as if we queried Wonder Woman 1984:
- https://www.rottentomatoes.com/m/wonder_woman_1984

@omdbapi: in #189 you wrote that this project is not discontinued -- could you please let us know:
- why such errors occur,
- how to deal with those, if not opening issues on Github,
- whether there is a better way?

thanks!

**Comment by tgreve15** [comment]
Check those entries in wikidata, perhaps whoever entered it there got it
wrong

**Comment by piramiday** [comment]
> Check those entries in wikidata, perhaps whoever entered it there got it wrong

I don't see why -- **omdb does not parse data from wikidata**, because I'm doing that in parallel and the results are different.

for example, wikidata reports the identifiers correctly for Tenet: https://www.wikidata.org/wiki/Q63985561

**Comment by omdbapi** [comment]
@piramiday Both of these entries have been fixed, the issue is caused when studios use code names (working titles) for movies and the data is stored before the final name.

To reduce data from disappearing if there is a non-NULL value it doesn't update it with the new title as sometimes the updated title can be wrong, the only fields that get updated regularly are ones that change a lot, votes, ratings, metascores etc.

**Comment by tgreve15** [comment]
According to other postings it pulls from Wikidata and other sources.
Perhaps this is not one of the wikidata things though.

**Comment by piramiday** [comment]
@omdbapi thanks for the reply. I don't understand how the process works, though.
1) are you maintaining your own database? can i find it somewhere? is it really **open** as in **O**mdb?
2) is there a way for users to contribute? e.g.: I know how to contribute to wikidata.
3) how is it possible that your algorithm connects unnamed movies from IMDb to RT?
