### ISSUE TITLE
this project seems discontinued

### ISSUE THREAD

**Issue by piramiday** [omdbapi/OMDb-API#189]
... prove me wrong! :safety_vest:

**Comment by blakethomp** [comment]
Curious what alternatives are out there... This covers almost all my needs, but I am just realizing the casting data is super limited, which is really unfortunate when the main actor/character doesn't even make the list.

**Comment by tgreve15** [comment]
One option is https://www.themoviedb.org/documentation/api
This one works from their own database but it seems more active and I
recall the public can contribute updates for data.

**Comment by omdbapi** [comment]
@piramiday Wrong!

**Comment by piramiday** [comment]
jokes aside, it does not look you are going through the issues in a timely fashion...
... which is perfectly human and understandable, mind you.

could you please provide some further info on how you are treating this project?

e.g.
I asked a question about wrong data here: #173 -- is there anything I should do, apart from asking you about it here?
