### ISSUE TITLE
{"Response":"False","Error":"Error getting data."} tt13046514

### ISSUE THREAD

**Issue by girod2033** [omdbapi/OMDb-API#204]
Hello!

Error.

http://omdbapi.com/?apikey=APIKEY&i=tt13046514

**Comment by M1VEC** [comment]
I'm getting the same error

**Comment by blitzher** [comment]
I'm getting a different error;
`{'Response': 'False', 'Error': 'Incorrect IMDb ID.'}`

**Comment by Ethorsen** [comment]
Getting the same response on some other ID
https://www.imdb.com/title/tt11729618/
http://www.omdbapi.com/?i=tt11729618&apikey=APIKEY

Is this something you guys have to fix one by one?

**Comment by omdbapi** [comment]
This is now fixed, there was some bots/scripts looping through tt13000000-tt99999999 ranges which until a week ago IMDb had nothing valid beyond tt12999999, so I was rejecting any request beyond that, it has now increased to the 14000000 range.

**Comment by iheathers** [comment]
I am getting the same issue now.

**Comment by tmiecz** [comment]
Hi there, just testing out the API. Do we need to bump the number up again? 
I'm getting the same error on this one:
https://www.omdbapi.com/?i=tt15196820

**Comment by andpro** [comment]
Also error for http://www.omdbapi.com/?i=tt18568902

**Comment by dev-adan** [comment]
hello i am getting error for http://www.omdbapi.com/?i=tt3896198

**Comment by ubadineke** [comment]
I'm also having issues fetching from your API, its showing incorrect IMDB Id

**Comment by ksyp-solulab** [comment]
I'm also getting same error for https://www.omdbapi.com/?i=tt3896198&apikey=******&i=tt1285016

**Comment by RitikSinghRawat** [comment]
same error please help

**Comment by omdbapi** [comment]
Looks like you are trying to request two ID's at the same time:

[image: image.png]

**Comment by morgue12free** [comment]
Hello mate, I'm having the same issue as the others. When I run: http://www.omdbapi.com/?apikey=9d6b56e3 

Appreciate your help in advance.
