### ISSUE TITLE
Wrong link sent in email

### ISSUE THREAD

**Issue by MGlolenstine** [omdbapi/OMDb-API#208]
I've just requested an API key, and received the following link in email
```
http://www.omdbapi.com/?i=tt3896198&apikey=<redacted>
```
but the API requires the `apikey` to be present before any other queries, so the API responds with 

```json
{"Response":"False","Error":"Invalid API key!"}
```

Correct link in this case would be
```
http://www.omdbapi.com/?apikey=<redacted>&i=tt3896198
```

**Comment by omdbapi** [comment]
Parameter order doesn't matter, this was most likely caused by clicking the example link before verifying the key which then caches the "Invalid API key" response.

**Comment by Furgas** [comment]
Yeah. I had the same problem. I propose moving "Click the following URL to activate your key" just after "Here is your key".
