### ISSUE TITLE
Title searches with "and" instead of "&" don't return results and searches with "&" don't return correct results

### ISSUE THREAD

**Issue by blairg23** [omdbapi/OMDb-API#216]
Example: `https://www.omdbapi.com?t=fast and furious&y=2009&plot=full`

returns

```
{
    "Response": "False",
    "Error": "Movie not found!"
}
```

In fact, the example with correct punctuation: `https://www.omdbapi.com?t=fast & furious&y=2009&plot=full`

returns the wrong result:

```
{
    "Title": "Fast",
    "Year": "2009",
    "Rated": "N/A",
    "Released": "28 Jul 2009",
    "Runtime": "N/A",
    "Genre": "Short, Sci-Fi",
    "Director": "Chin Yu",
    "Writer": "Chin Yu",
    "Actors": "Chin Yu, DaYoung 'Dada' Kim, Sou Chang, Jimmy York",
    "Plot": "N/A",
    "Language": "English",
    "Country": "USA",
    "Awards": "N/A",
    "Poster": "https://m.media-amazon.com/images/M/MV5BNTE4MTc4OTk4OV5BMl5BanBnXkFtZTcwNjU3MTM5OQ@@._V1_SX300.jpg",
    "Ratings": [],
    "Metascore": "N/A",
    "imdbRating": "N/A",
    "imdbVotes": "N/A",
    "imdbID": "tt1872058",
    "Type": "movie",
    "DVD": "N/A",
    "BoxOffice": "N/A",
    "Production": "N/A",
    "Website": "N/A",
    "Response": "True"
}
```

**Comment by vageliskatsiotis** [comment]
Hi blairg23.

If you use the Examples Section on http://www.omdbapi.com/ you'll notice that the url used on search,  turns & to %26 which is the ASCII character for &, and is connected to the other words with + .

So, the correct string for searching this would be like below, as the movie's title is "Fast & Furious" and not "Fast and Furious", 

http://www.omdbapi.com/?t=Fast+%26+Furious

Your second example returns the correct result as you search for "fast" only, as it turns out.

**Comment by blairg23** [comment]
That still seems like a bug, the point of an API is to abstract the logic for the user to make it simpler. You shouldn't have to do preprocessing of your search strings before using the API.

**Comment by Lucky-Loek** [comment]
@blairg23 it is, however, how the internet works and the author of OMDb can't really change that. Ampersands (`&`) have special meaning in URLs: https://stackoverflow.com/questions/38252310/what-do-a-question-mark-and-an-ampersand-mean-in-a-url

**Comment by blairg23** [comment]
Read the original issue. If the title of a film has `&` in the title and you use the word `and`, it doesn't return results. How are you then supposed to search for titles with `&` in the title? Use unicode encoding?

**Comment by Lucky-Loek** [comment]
By urlencoding them, as suggested in the first answer. You can use built-in functions in your programming languages, libraries or tools like https://www.urlencoder.io/

**Comment by blairg23** [comment]
Fair enough
