### ISSUE TITLE
Get list of results instead of single result

### ISSUE THREAD

**Issue by danieledwardharrington** [omdbapi/OMDb-API#217]
I'm using the API for an Android app to learn a bit more about Retrofit and some other stuff. What I want to do is have the user search for a movie by title and have it be a live search, where there are options as the user types. It seems like the API only returns one movie at a time. Is this correct? Or am I missing something in order to get a list of movies that match the query? The website doesn't seem to say anything about this. Even a super vague query seems to just return one result. When I just search j, only J. Edgar is returned rather than several results that satisfy j.

As an example, my idea is honestly kind of like how IMDb handles search, if you've used the app. Thanks for any help!

**Comment by sandeepkambham08** [comment]
You can use the "s" parameter - which is for search. 
Example: https://www.omdbapi.com/?&apikey=xxxxxx&s=fast
This returns the titles containing "fast" in them

You can also add the page number parameter "p" to get movies from the next page(as it will return page 1 with ~10 titles).
