### ISSUE TITLE
Page parameter does not work(?)

### ISSUE THREAD

**Issue by aecceyhan** [omdbapi/OMDb-API#229]
Hi,

I try to get the list of StarWars movies with CRUL

`curl --location --request GET 'https://www.omdbapi.com/?t=starwars&apikey=KEY&plot=full&page=1' 

and

`curl --location --request GET 'https://www.omdbapi.com/?t=starwars&apikey=KEY&plot=full&page=2' 

When change the page parameter does not affect the result. Is this a bug or do I use this thing wrong? Also is there any way to get a list of movies on search?

**Comment by arturacm** [comment]
Hey, 
from what I understood  from this API, the page option is  only availible if you are doing a Search.
Try intead of the key T using the key S.
Then the page key will become availible.

**Comment by omdbapi** [comment]
Thank you @arturacm for answering this.
