### ISSUE TITLE
Service is down

### ISSUE THREAD

**Issue by alexandergre** [omdbapi/OMDb-API#237]
Currently getting http error 522 (origin connection timeout) when trying to invoke the api.

**Comment by nivlev2** [comment]
Do you know when it should back to work?

**Comment by bhubhik** [comment]
> Currently getting http error 522 (origin connection timeout) when trying to invoke the api.

Same here in Sydney

**Comment by alexandergre** [comment]
Looks like it's back to normal, for me at least
