### ISSUE TITLE
[Documentation] List of possible genres

### ISSUE THREAD

**Issue by weirdyang** [omdbapi/OMDb-API#244]
Is there a list of all the genre types?

**Comment by owenashurst** [comment]
+1 

I think we need some sort of search for genre so we can get a list of all film/episode/tv shows back.

**Comment by weirdyang** [comment]
For anyone interested, I have the list here https://github.com/weirdyang/movie-therapy-angular/blob/feature/filter-menu/src/assets/shows/genres.json

**Comment by MikeyA-yo** [comment]
hey @weirdyang is there a way i can filter out movies from omdb api based on genre?

**Comment by weirdyang** [comment]
> hey @weirdyang is there a way i can filter out movies from omdb api based on genre?

I don't think so

**Comment by MikeyA-yo** [comment]
> > hey @weirdyang is there a way i can filter out movies from omdb api based on genre?
> 
> I don't think so

yh, but in your web you did it some how, how did you go about it?

**Comment by weirdyang** [comment]
> > > hey @weirdyang is there a way i can filter out movies from omdb api based on genre?
> 
> > 
> 
> > I don't think so
> 
> 
> 
> yh, but in your web you did it some how, how did you go about it?

I scraped the movies I needed, then filtered that. I got the list of genres from checking both imdb and omdbapi

**Comment by MikeyA-yo** [comment]
> > > > hey @weirdyang is there a way i can filter out movies from omdb api based on genre?
> > 
> > 
> > > 
> > 
> > 
> > > I don't think so
> > 
> > 
> > yh, but in your web you did it some how, how did you go about it?
> 
> I scraped the movies I needed, then filtered that. I got the list of genres from checking both imdb and omdbapi

oh i see, i can't get imdb api cause it requires aws, thanks anyways
