### ISSUE TITLE
XML Response bug

### ISSUE THREAD

**Issue by duckdoom5** [omdbapi/OMDb-API#27]
XML readers are case sensitive. 
When the Response value is false the attribute name is "Response"
If it's true the attribute name is "response"

http://www.omdbapi.com/?apikey=[key]&r=xml&type=series&s=l
http://www.omdbapi.com/?apikey=[key]&r=xml&type=series&s=lucifer

Because of this the code breaks when looking for lower case response and receiving upper case:
```
string s = xReader.GetAttribute("response");
```

**Comment by omdbapi** [comment]
Fixed.
