### ISSUE TITLE
Error : Incorrect IMDB ID

### ISSUE THREAD

**Issue by MDoughlin** [omdbapi/OMDb-API#297]
I am making a call to the API and I am searching by the movie title, not the ID number and keep getting the following error 

Error: "Incorrect IMDb ID."
Response: "False"

My api key I have taken out and put [yourkey] where it should go
    fetch(`http://www.omdbapi.com/?apikey=[yourkey]=${value}`)

**Comment by songcengiz** [comment]
Instead of using: "https://www.omdbapi.com/?apikey=[API KEY]&s=Interstellar"

use: "https://www.omdbapi.com/?s=Interstellar&apikey=[API KEY]".

And also, make sure that your key is activated.
