### ISSUE TITLE
Service is Down (HTTP 522)

### ISSUE THREAD

**Issue by buckedunicorn** [omdbapi/OMDb-API#312]
Hello,

Thank you for providing this free service. I wanted to let you know it appears to be down.

**Comment by jzrlqwzy** [comment]
I got Error 522 just now, not sure if it's my network connection...

**Comment by Unknown-Blaze** [comment]
Yes same, unfortunately it's not network connection as I've asked around and no one is able to run it. Not able to access the API key link either.

**Comment by buckedunicorn** [comment]
The service is now back up. Closing issue.
