### ISSUE TITLE
Error getting data for some movies

### ISSUE THREAD

**Issue by peymanr34** [omdbapi/OMDb-API#47]
For some movies API returns following error:

`{"Response":"False","Error":"Error getting data."}`

tt7241928
tt6389320

**Comment by omdbapi** [comment]
Those are very obscure movies that I couldn't find on TMDb or Wikidata.org.

If you manually add them to Wikidata.org they will eventually propagate to my API and be available.

The OMDb API databases has MILLIONS of movies but nowhere near the catalog of IMDb.
