### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by YogaCr** [omdbapi/OMDb-API#48]
I got error 403 even I can open it in browser

**Comment by josezulu** [comment]
Can you please provide information as to what you were trying to do or access when you got the error?

**Comment by YogaCr** [comment]
it works now
Yesterday, I can't access the API.
But,after I waited for 2-3 hours,it worked

2018-02-11 23:49 GMT+07:00 Josar <notifications@github.com>:

**Comment by omdbapi** [comment]
@sakatayoga the error had to be coming from Cloudflare as the API currently doesn't have any code paths that return a 403 error.

Glad to hear it's working now.
