### ISSUE TITLE
Timeouts when using Year

### ISSUE THREAD

**Issue by tanner-rutgers** [omdbapi/OMDb-API#50]
Ever since I've added the `y` query parameter for querying by year, I get significantly more timeouts from the service. Before passing `y` I was passing title (`t`), and sometimes season/episode (`Season` and `Episode`) and rarely if ever received a timeout while querying. Now I'm seeing roughly 1/10 queries fail after a delay of 10+ seconds.

Why does adding the `y` query param cause these timeouts?

**Comment by omdbapi** [comment]
I'm working with CloudFlare to get this resolved but need to know if you are experiencing a 524 or a 522 timeout error.

Also, are you using HTTPS?

**Comment by josezulu** [comment]
I turned HTTPS back on to test this, I get error 524: "Origin Time-out".

Interestingly enough, it seems to be indeed related to searching with the year parameter !!!

Yes, tried it three times now, all 3 times I added the year parameter the search timed out!

@tanner-rutgers nice find!

**Comment by omdbapi** [comment]
Hey @josezulu,

I just enabled the Argo service with Cloudflare that is supposed to fix all of these timeout issues.

Please run your tests again and let me know the outcome. Thanks

**Comment by josezulu** [comment]
Hi @omdbapi 

Thank you for looking into this! I've been testing this evening with https, I've run queries with and without the year parameter, and I didn't get any timeout errors so far !!!

I'll continue using https for a couple of days, I'll keep you posted, whether timeouts or otherwise.

**Comment by josezulu** [comment]
Hi @omdbapi 

I've used https for 4 evenings now, I have only seen a timeout once, I've tested with and without year parameter, this seems to be a great improvement.
Additionally, I've noticed that response times went down drastically, from about 500ms to below 100ms. I would guess the service you contracted does some caching which reduces the timing.

Thanks for working on addressing this issue, I understand this is not a cheap fix.

Just something I want to mention: when I get 524 timeouts, I repeat the query and I get a response just fine. So I could guess that my request did arrive, the processing did take place, but the response was never sent back to me. Something to look into perhaps when looking for an alternative fix? Also, the fact this issue tends to me more prominent when adding the year parameter to a query.

**Comment by josezulu** [comment]
Hi @omdbapi 

Just FYI, further feedback: I had a 524 origin timeout just now.
The parameters included in the request were: i=tt2557478, plot=full, r=json, tomatoes=true, apikey=###

I repeated the request, and got the response at normal timings.
The time outs seems to be now isolated issues, much much less frequency than before.

**Comment by omdbapi** [comment]
Hey @josezulu 

Thanks for the update, I'm 100% sure any timeouts you are seeing are now solely caused by the "**tomatoes=true**" parameter which is still trying to access an API that is no longer active.

I'll push an update soon that will address this.

**Comment by josezulu** [comment]
Hey @omdbapi,

Oh ok, cool thanks for the info!

**Comment by josezulu** [comment]
Hi @omdbapi ,

I was about to update my code to stop using **"tomatoes=true"**, but that would break things as I rely on **_".tomatoURL"_** to get the rotten tomatos' url for the title.

I realise this can break others' implementations as well.

**Comment by tanner-rutgers** [comment]
Thanks for fixing @omdbapi and thanks for the help investigating @josezulu!! Apologies, I was MIA for a while and forgot I created this issue. Sounds like it's resolved now, at least the `y` parameter issue, so I'll go ahead and close this issue :)
