### ISSUE TITLE
Episodes list not up to date

### ISSUE THREAD

**Issue by Morusec** [omdbapi/OMDb-API#54]
Hi!

I just created a key and tested this call:
http://www.omdbapi.com/?apikey=[key]&t=tt2357547&season=2

It should list all 13 episodes of Jessica Jones second season but only lists 3 random episodes (1st, 7th and the last one)

Is there a way to force a refresh somehow?

Thank you!

**Comment by Morusec** [comment]
Bump?

**Comment by omdbapi** [comment]
Fixed!
