### ISSUE TITLE
A 401 appears when trying to use the example API call

### ISSUE THREAD

**Issue by blairg23** [omdbapi/OMDb-API#55]
**As far as I can tell, there's no way to authenticate into the website when visiting http://omdbapi.com, yet when trying to use the example, it sends the following request:** 

http://www.omdbapi.com/?i=tt0108941&apikey=PlsBanMe

**which results in a 401 and the following response message:**

`{"Response":"False","Error":"Request limit reached!"}`

**Side note: I have paid for an API key.**

**See screenshot for detail from UI:**

![image](https://user-images.githubusercontent.com/6225764/37455240-3e1cf38e-2802-11e8-9cc9-2d2ea517f231.png)

**Comment by omdbapi** [comment]
The actual issue is it's not returning a proper 403 error when the request limit is reached.

**Comment by blairg23** [comment]
When someone is using the example api calls from the website, should they
ever receive this? For me it was after 2 example calls. The point of a
sandbox is to allow the user to see examples...?

**Comment by blairg23** [comment]
This is still a valid issue. I tried to use the example API call for the first time today and got this message:

![image](https://user-images.githubusercontent.com/6225764/41572920-6fe2091a-7337-11e8-8bc3-56fb021f63d3.png)

Upon clicking the link, I get this: 

![image](https://user-images.githubusercontent.com/6225764/41572935-7dbd4414-7337-11e8-8db3-02ab0af37e76.png)

Yet there is no way to enter credentials or an API key in the example UI, so this is a really bad UX issue.
