### ISSUE TITLE
Issue with tt8234468

### ISSUE THREAD

**Issue by mmvcode** [omdbapi/OMDb-API#57]
When calling for the following title:

`http://www.omdbapi.com/?apikey={my_key}&i=tt8234468`

The following error is returned by the API:
`{"Response":"False","Error":"Error getting data."}`

This is also the case when using the test forms on your website,

**Comment by omdbapi** [comment]
I'm not finding this title on any other API (TMDb, Wikidata etc.).

Just because IMDb has it doesn't mean OMDb will (a common misconception).

**Comment by mmvcode** [comment]
https://www.themoviedb.org/tv/78578-mountain
