### ISSUE TITLE
Episodes return N/A for Season or Rating

### ISSUE THREAD

**Issue by stedy** [omdbapi/OMDb-API#6]
`/tt0589862` returns "N/A" for Rated, Season and Episode while another episode from that same season `/tt0589807` returns all values normally. Any ideas why this might be happening?

**Comment by omdbapi** [comment]
**This has been fixed!** Not many people request "The Golden Girls" therefore the cached data was outdated and missing ratings and its associated Series ID etc.

I forced an update on the entire series, but I really need to rework my update logic for real-time requests also.

**Comment by stedy** [comment]
Glad Dorothy, Blanche, Rose and Sophia were a good test case. I am afraid the issue might go beyond this show as I found a similar issue with a more recent show: `/tt3978930`

**Comment by omdbapi** [comment]
BoJack! That has also been updated, it might take awhile for you to see the results due to Cloudflare caching. Keep em coming!

**Comment by Almenon** [comment]
http://omdbapi.com/?apikey=secret&t=agents%20of%20s.h.i.e.l.d.&Season=5&Episode=16

```"Ratings":[],"Metascore":"N/A","imdbRating":"N/A","imdbVotes":"N/A","imdbID":"tt7183120","seriesID":"tt2364582","Type":"episode","Response":"True"}```
