### ISSUE TITLE
Server returned 503 Service Unavailable

### ISSUE THREAD

**Issue by Anan5a** [omdbapi/OMDb-API#69]
## It broke my application :(
# Please fix it
![orca-image-1527423926711 jpg_1527423927044](https://user-images.githubusercontent.com/16373480/40586065-c4311d3c-61dd-11e8-959b-dccc775d67ed.jpeg)

**Comment by MAGICCC** [comment]
Seems the server is currently down. Just try it again later
https://httpstatuses.com/503

**Comment by josezulu** [comment]
I've been having the same issue for almost 3 hours.

**Comment by eliehaykal** [comment]
There seems to be some instability issue.

**Comment by omdbapi** [comment]
Cloudflare DNS was having routing issues which caused this issue.

Everything is working fine now.
