### ISSUE TITLE
Lacking a forum: Using this Issues tracking as a discussion forum

### ISSUE THREAD

**Issue by axa88** [omdbapi/OMDb-API#71]
I need to ask a question and feel there is something just wrong about doing it here.
Is there not a proper forum somewhere?

Anyway, curious why this request doesn't return anything.
Seems it is a proper imdb movie id
http://www.omdbapi.com/?apikey=*******&t=tt0066921&type=movie&plot=full

im a noob, what don't i know?

**Comment by josezulu** [comment]
Your “t” parameter should contain a title, not an imdb id.

Try “t=the matrix”

If you want to get results for an imdb id, use “i=“.
