### ISSUE TITLE
Incorrect description for steven universe s1e7 & s1e10

### ISSUE THREAD

**Issue by Almenon** [omdbapi/OMDb-API#72]
http://omdbapi.com/?apikey=secret&t=steven%20universe&Season=1&Episode=7

Expected:

> [Steven tries to work up the courage to talk to a girl on the beach.](https://www.imdb.com/title/tt3600972/?ref_=ttep_ep8)

Actual:

> So Many Birthdays: Steven learns that the Crystal Gems are thousands of years old and decides to make up for all the thousands of birthdays they've missed. / Lars and the Cool Kids: Steven ...

The same thing for episode 10 - the description is from a different episode.  It should be "Steven finds a magical lion in the desert."

http://omdbapi.com/?apikey=secret&t=steven%20universe&Season=1&Episode=10

*(replace "secret" with working apikey)*

**Comment by omdbapi** [comment]
This seems to be fixed.
