### ISSUE TITLE
Some IMDb ID don't work! 

### ISSUE THREAD

**Issue by Anan5a** [omdbapi/OMDb-API#74]
### Here are 2 of them I encountered 
```
https://m.imdb.com/title/tt8412178/
https://m.imdb.com/title/tt3638960/
```
## Can you explain the reason? It'll be helpful :)

**Comment by grctest** [comment]
The error you're getting is ```{"Response":"False","Error":"Error getting data."}```

I'm getting this error for approximately 60502 movies: https://raw.githubusercontent.com/know-ail/Vote-Goat-Data/master/omdbapi-python-tool/data/60.5k_omdb_errors.txt

@omdbapi please fix these entries 👍

**Comment by Anan5a** [comment]
@omdbapi It's been 1 month+ Still no fix?

**Comment by omdbapi** [comment]
The API does not contain every IMDb ID, many obscure titles will be missing.

You can manually add things to the API by updating Wikidata.org

**Comment by tgreve15** [comment]
I wouldn't be surprised if this also has to do with the frequency the data
is updated from imdb. The newer imdb items wouldn't exist if created since
last refresh.

**Comment by Anan5a** [comment]
@omdbapi Can't you just crawl on demand? Because that will be really great.
Like this
```
REQUEST -> NO EXISTENCE OF DATA || DATA TOO OLD -> RE CRAWL -> STORE AND SERVE
```
Just saying :)
