### ISSUE TITLE
I can't reopen an issue, but this is related to https://github.com/omdbapi/OMDb-API/issues/55

### ISSUE THREAD

**Issue by blairg23** [omdbapi/OMDb-API#76]
This is still a valid issue, please see my comment on https://github.com/omdbapi/OMDb-API/issues/55

**Several issues:**

1. There is no way to authenticate real users on the example API call (I am a Patreon yet I'm given an error message upon trying to send an example call).
2. If it's an example sandbox to test out the API, then it shouldn't even have a limit.
3. I hit the limit on my first attempt to use it.

**Comment by omdbapi** [comment]
1. The example on the homepage is not supposed to be used as a sandbox.
2. The reason the limit was hit is due to people abusing it.
3. The reason there is a limit on it is due to the people abusing it.
