### ISSUE TITLE
Poster for Escape Plan 2: Hades (2018) results in a 404

### ISSUE THREAD

**Issue by blairg23** [omdbapi/OMDb-API#77]
This is probably a bug in imdb, but not sure how we rectify it on our end.

**Invalid link:**
https://ia.media-imdb.com/images/M/MV5BMjRkZGY3ZTctMTY4NS00ODAwLWE2MTctYmE1MjAyMGRkMGZkXkEyXkFqcGdeQXVyNDMzMTkyOQ@@._V1_SX300.jpg

**Valid link:**
https://m.media-amazon.com/images/M/MV5BMTk4NjA0MjUyMF5BMl5BanBnXkFtZTgwMTEzNDQ1NTM@._V1_SY1000_CR0,0,666,1000_AL_.jpg

**Comment by omdbapi** [comment]
I would recommend getting posters from the Poster API and not using the IMDb/Amazon links in the JSON results.
