### ISSUE TITLE
Insecure Content Blocked

### ISSUE THREAD

**Issue by sabriele** [omdbapi/OMDb-API#78]
I am trying to create a Search Bar using Semantic UI's [Search module](https://semantic-ui.com/modules/search.html#using-api-settings) and the OMDB API but when I deploy my site on Heroku, my Search bar breaks (it works fine on localhost). In the URL bar, Chrome informs me that I cannot run the Semantic API script because "Insecure Content Blocked: This page is trying to load scripts from unauthenticated sources."

MDN tells me that this may be a problem of mixed content and that to [fix it](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content#How_to_fix_your_website) I should serve all my content as HTTPS instead of HTTP.

On the OMDB homepage, it clearly states that we should "Send all data requests to: **http**://www.omdbapi.com/?apikey=[yourkey]&". Should this/can this be fixed?

**Comment by jagDanJu** [comment]
Hey,

the api works with https:// well. Give them a try
I can not recognize any differences.

Anyway, the homepage should be fixed

**Comment by omdbapi** [comment]
HTTPS is also supported.
