### ISSUE TITLE
Majority of movies have 'N/A' for age rating?

### ISSUE THREAD

**Issue by grctest** [omdbapi/OMDb-API#80]
Out of approx 250k movies I've looked at, 191838 movies have 'N/A' for their age rating.

Is this actually the case? I'd have thought that all/most content on IMDB would get an age rating, but perhaps movies get partly made or go straight to dvd without any age rating being applied/required?

Makes it tough to quickly filter out inappropriate/adult content.

**Comment by omdbapi** [comment]
Obscure movies tend not to have MPAA ratings, I'm sure most (if not all) adult content is rated however.
