### ISSUE TITLE
Nathan For You Season 2 returns error

### ISSUE THREAD

**Issue by ghost** [omdbapi/OMDb-API#81]
'https://www.omdbapi.com/?t=nathan%20for%20you&y=2013&season=2&apikey=APIKEY'

returns: {"Response":"False","Error":"Series or season not found!"}

There are also episodes missing when I search for season 1. Is this happening with other shows too?

**Comment by thereido** [comment]
FYI, this succeeded in a browser (Firefox) today...
https://www.omdbapi.com/?apikey=APIKEY&v=1&t=nathan%20for%20you&y=2013&season=2

**Comment by omdbapi** [comment]
Fixed
