### ISSUE TITLE
Movie Poster Not Updated

### ISSUE THREAD

**Issue by fishcharlie** [omdbapi/OMDb-API#83]
The IMDb ID `tt3606756` poster is not updated. If you get the `Poster` from the JSON data and go to that URL, the poster is much more updated than the one on the OMDb Poster endpoint. On the OMDb website it says `Currently over 280,000 posters, updated daily...`. It shouldn't say `updated daily` if the posters are outdated compared to the data API.

**Comment by omdbapi** [comment]
The poster link in the JSON response is sometimes worse than what the Poster API provides. Each one has to be manually reviewed by a human, I don't think A.I. is quite there yet to decide which poster is visually better :)

I updated this specific ID (Incredibles 2) to a better poster, I'll try to keep on top of newer releases moving forward.
