### ISSUE TITLE
Single data is returned from API

### ISSUE THREAD

**Issue by sercanbyt** [omdbapi/OMDb-API#84]
hi,
i have search to title but single data is returned from api
http://www.omdbapi.com/?t=myKeyword&apikey=myApikey

i need list of data, but only return single data. if i search only with keyword like that ;
http://www.omdbapi.com/?s=myKeyword&apikey=myApikey

return list of data but some data is missing, for example; rate of movie etc not find in data.

help pls
best wishes

**Comment by omdbapi** [comment]
Once you have the ID's from your search results (**?s=**) you would have to query each one to get the full details.
