### ISSUE TITLE
"Response":"False","Error":"Something went wrong."

### ISSUE THREAD

**Issue by karlokralj** [omdbapi/OMDb-API#85]
I get this error when i link my api key to my web page, maybe I am doing it wrong i just linked it like this in my html <script src="http://www.omdbapi.com/?apikey=(mykeygoeshere)></script>

**Comment by dewey** [comment]
What are you trying to do? I guess you'll need some query parameters to do a lookup of some sorts.

**Comment by karlokralj** [comment]
well i completly messed up, sorry for a dumb question, got it working

**Comment by MAGICCC** [comment]
Exposing an API key to a public webpage isn't a great idea...

**Comment by karlokralj** [comment]
And where did I do that?

**Comment by dewey** [comment]
You didn't do it right now as you used a place holder. But if you actually embed it into the <script> tag on a website everyone is going to see it.

**Comment by karlokralj** [comment]
Oh well yes, I didn't include it in the script tag i completly scraped that and i included it in my request call directly. 
It would be a mistake tho, ty for explaining
