### ISSUE TITLE
CAPTCHA and Allow-Control-Allow-Origin

### ISSUE THREAD

**Issue by isabolic** [omdbapi/OMDb-API#86]
Hi,

I'm testing your API and I keep getting google CAPTCHA as prompt at first, my guess this is because of "Cloudflare" also there is no header for "Allow-Control-Allow-Origin:*" from server response...

example:
http://www.omdbapi.com/?s=fight&apikey=MYKEY

Best regards
isabolic

**Comment by omdbapi** [comment]
You are triggering one of the Cloudflare OWASP rules.

I would need the Ray ID number displayed on the CAPTCHA page to find out why it's happening.

**Comment by isabolic** [comment]
Hi,

since last Tuesday everything is working ok. Nothing change from my part.

Best regards
isabolic

**Comment by sashas777** [comment]
@isabolic 
I have the same issue: Cloudflare Ray ID: 49d02bd8907391a6
