### ISSUE TITLE
Search by Title doesn't return expected result in some cases

### ISSUE THREAD

**Issue by svzi** [omdbapi/OMDb-API#88]
Hi @omdbapi,

first of all thanks for making this great API! Today I've discovered a bug, at least from my point of view, because the API doesn't return the expected result from a title based search:

`http://www.omdbapi.com/?apikey=xxx&t=Afflicted&y=2018` => `{"Response":"False","Error":"Movie not found!"}`

Going to imdb.com and searching for "Afflicted" delivers several results, one for the year 2018:
https://www.imdb.com/title/tt8792570/

That is the one I'm looking for. Could you please check your API and tell me what's going wrong?

Thanks a lot!

Best,
Sven

**Comment by svzi** [comment]
Another example is the series "Insatiable" from 2018. No matter what I try to find it, the API doesn't return the expected entry from 2018:

`http://private.omdbapi.com/?apikey=xxx&s=Insatiable&y=2018`
`http://private.omdbapi.com/?apikey=xxx&s=Insatiable`
`http://private.omdbapi.com/?apikey=xxx&s=Insatiable&type=series`
`http://private.omdbapi.com/?apikey=xxx&t=Insatiable&y=2018`
`http://private.omdbapi.com/?apikey=xxx&t=Insatiable`
`http://private.omdbapi.com/?apikey=xxx&t=Insatiable&type=series`
...

But on IMDB it's available as well:
https://www.imdb.com/title/tt6487482/

**Comment by dausruddin** [comment]
I had this issue quite frequently back then forcing me to use scraper instead. Seems that omdbapi's database is rarely updated resulting in this issue, or maybe something else. Data are outdated and new movies added to imdb have low chances to be found in omdbapi.

**Comment by svzi** [comment]
I would expect at least some kind of support from @omdbapi ! I'm starting to ask my self why I support this project on Patreon, when I don't get support...

**Comment by omdbapi** [comment]
@svzi Just because it's on IMDb doesn't mean my API will have it, I get data from a lot of different sources, none of which are IMDb.

These titles (Afflicted, Insatiable) were shortly added to Wikidata.org after you opened this issue (https://www.wikidata.org/wiki/Q56054858) of which my API was automatically updated the next time they were requested.
