### ISSUE TITLE
Feature request: omdb.org URL

### ISSUE THREAD

**Issue by TomBraider42** [omdbapi/OMDb-API#89]
Could you add the omdb.org URL to the result?
e.g. `https://www.omdb.org/movie/10373-quadrophenia`
or just `/movie/10373-quadrophenia`

**Comment by dewey** [comment]
AFAIK these two projects are not affiliated. OMDB.org is a TMDB alternative while OMDBAPI is an open wrapper around IMDB data.

**Comment by TomBraider42** [comment]
OK, i thought omdbapi is an api for omdb.
