### ISSUE TITLE
To Be Aired episodes not part of result ?

### ISSUE THREAD

**Issue by coder-alpha** [omdbapi/OMDb-API#90]
A lot of shows don't seems to show the listing for the TBA episodes and also don't seem to get updated. The S4E01 was aired on Aug. 08 but still does not show that info while IMDB has data for much further ahead. Please look into this. Thanks.

http://www.omdbapi.com/?i=tt3032476&Season=3&apikey=[apikey]
`{"Title":"Better Call Saul","Season":"3","totalSeasons":"5","Episodes":[{"Title":"Mabel","Released":"2017-04-10","Episode":"1","imdbRating":"8.3","imdbID":"tt5554490"},{"Title":"Witness","Released":"2017-04-17","Episode":"2","imdbRating":"9.1","imdbID":"tt5579594"},{"Title":"Sunk Costs","Released":"2017-04-24","Episode":"3","imdbRating":"8.7","imdbID":"tt5719532"},{"Title":"Sabrosito","Released":"2017-05-01","Episode":"4","imdbRating":"9.1","imdbID":"tt5719534"},{"Title":"Chicanery","Released":"2017-05-08","Episode":"5","imdbRating":"9.8","imdbID":"tt5719536"},{"Title":"Off Brand","Released":"2017-05-15","Episode":"6","imdbRating":"8.8","imdbID":"tt5719540"},{"Title":"Expenses","Released":"2017-05-22","Episode":"7","imdbRating":"8.5","imdbID":"tt5719542"},{"Title":"Slip","Released":"2017-06-05","Episode":"8","imdbRating":"8.8","imdbID":"tt5719546"},{"Title":"Fall","Released":"2017-06-12","Episode":"9","imdbRating":"9.0","imdbID":"tt5719544"},{"Title":"Lantern","Released":"2017-06-19","Episode":"10","imdbRating":"9.2","imdbID":"tt5570804"}],"Response":"True"}`

http://www.omdbapi.com/?i=tt3032476&Season=4&apikey=[apikey]
`{"Title":"Better Call Saul","Season":"4","totalSeasons":"5","Episodes":[{"Title":"Episode #4.1","Released":"N/A","Episode":"1","imdbRating":"N/A","imdbID":"tt7073996"}],"Response":"True"}`

**Comment by omdbapi** [comment]
I'm working on improving the frequency active shows are updated.

This particular one has also been recently updated.
