### ISSUE TITLE
Search by tittle it always return 10 results only

### ISSUE THREAD

**Issue by pannerdass** [omdbapi/OMDb-API#91]

**Comment by tgreve15** [comment]
I just keep calling the search function with an incrementing page counter like you have used until I don’t get a response, “Response” is False, or I hit a limit I set in my program. If there are 3721 results, do you want them all? Or, do you want to wait until you have them all back before displaying something?

From: pannerdass
Sent: Thursday, August 16, 2018 4:48 AM
To: omdbapi/OMDb-API
Cc: Subscribed
Subject: [omdbapi/OMDb-API] Search by tittle it always return 10 results only(#91)

While Search any movie it will return only 10 results,how to get all results.
But it shows totalResults:3721
http://www.omdbapi.com/?s=dead&page=77&apikey=xxxx

**Comment by omdbapi** [comment]
Working as intended.

**Comment by santhoshramos** [comment]
what does it mean

**Comment by rohitnitk** [comment]
How to get more than 10?

**Comment by josh231101** [comment]
I want to get just 5 results or sort of specify to get 3,5,10 somethin like that,,,,,

**Comment by kalleftw** [comment]
> I want to get just 5 results or sort of specify to get 3,5,10 somethin like that,,,,,

http://www.omdbapi.com/?apikey=APIKEY&s=${SEARCH}&page=${PAGENUMBER}

**Comment by baraaNoman** [comment]
> How to get more than 10?

you can add more than one page , each page has only 10 .

**Comment by ardiyantop8** [comment]
I want to get only 5 data in 1 page, is there a limit parameter?

**Comment by tgreve15** [comment]
I don't believe you can change the page size, I recall you get the total
number of results, so if you want to display 5 results per pages you'll
need to create your own caching mechanism and retrieve extra data as you
need it, storing the extra 5 records yourself ready for the user.

**Comment by anshul0077** [comment]
yes , the  same issue is faced i call the OMDB api for a particular search it will only return 10 result but it will show 321 total result ;

**Comment by tgreve15** [comment]
Per [kalleftw](https://github.com/kalleftw) post above, the API allows you to pass a &page= parameter. You know there are 321 results, you make this request as many times as you need (33?) increasing the page you are looking for each time ....

**Comment by anshul0077** [comment]
Thankyou , its working now i add the pagination and then it give the result after the another page
