### ISSUE TITLE
Search for people

### ISSUE THREAD

**Issue by vasyl-shumskyi** [omdbapi/OMDb-API#93]
I would like to search for all movies by the certain director.  Is it possible with OMDb-API? 

For example, see following IMDB page with Stanley Kubrick works:

https://www.imdb.com/name/nm0000040/?ref_=fn_al_nm_1

Thanks

**Comment by vasyl-shumskyi** [comment]
Rel #37

**Comment by omdbapi** [comment]
Dupe of #37
