### ISSUE TITLE
Incorrect returned movie search results. 

### ISSUE THREAD

**Issue by zhiiiyang** [omdbapi/OMDb-API#94]
When I searched for Skate Kitchen and Madeline's Madeline, both return "Movie not found!".

**Comment by imrehg** [comment]
Now there's a result for `Skate Kitchen`. Both are 2018 movies, so maybe too new, and takes some time to sync? Probably just have to wait a bit.

**Comment by zhiiiyang** [comment]
That makes sense. Thank you!
