### ISSUE TITLE
OpenSource

### ISSUE THREAD

**Issue by quentincaffeino** [omdbapi/OMDb-API#95]
Good day,

Have thought about making backend opensource?
This could improve development speed and user involvement.

Best

**Comment by omdbapi** [comment]
I'm thinking of making the Poster API opensource but not the OMDb API.

**Comment by quentincaffeino** [comment]
@omdbapi, api even doesn't have proper search, why not?

**Comment by dewey** [comment]
@QuentinCaffeino What kind of question is that? He doesn't owe you anything, if you can build something better than go ahead and open source it. Not open sourcing could have a million valid reasons.

**Comment by quentincaffeino** [comment]
@omdbapi, I must apologize, I'm not a native speaker, that question sounded ok for me.
@dewey the main problem is: I don't have the database, and the second is: why create another one.
That's why I suggested making it opensource.
